# Site Settings
title: Bootstrapbase.com
email: contact@bootstrapbase.com
description: > # this means to ignore newlines until "baseurl:"
  Bootstrapbase.com, free and premium bootstrap themes, templates and wireframes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bootstrapbase.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
permalink: pretty

#Site Details
license: ""
license-url: ""
author: "Bootstrapbase"

# Jekyll Redirect From Plugin for Redirects from redirect_from in template-overviews/blog-with-sidebar
gems:
  - jekyll-redirect-from